<<<<<<< HEAD
theme: jekyll-theme-minimal
title: BluetoothProximity
description: BluetoothProximity is an MIT research application
logo: /assets/App_Icon_470.png
=======
theme: jekyll-theme-minimal
>>>>>>> ffc235894e6437ed5212b93ac65a1a542b380f72
